export const domain = "streamingoverlays-3f50d.web.app";

export const fontFamilies = [
  "Roboto, sans-serif",
  "Open Sans, sans-serif",
  "Lato, sans-serif",
  "Montserrat, sans-serif",
  "Nunito, sans-serif",
  "Poppins, sans-serif",
  "Roboto Slab, serif",
  "Source Serif Pro, serif",
  "Merriweather, serif",
  "Oswald, sans-serif",
  "PT Sans, sans-serif",
  "IBM Plex Sans, sans-serif",
  "IBM Plex Mono, monospace",
  "Cutive Mono, monospace",
  "Playfair Display, serif",
  "Bebas Neue, sans-serif",
  "Raleway, sans-serif",
  "Fira Sans, sans-serif",
  "Ubuntu, sans-serif",
  "Inconsolata, monospace",
  "Alegreya, serif",
  "Cormorant, serif",
  "Quicksand, sans-serif",
  "Amatic SC, cursive",
  "Pacifico, cursive",
  "Dancing Script, cursive",
  "Cinzel, serif",
  "Libre Baskerville, serif",
  "Garamond, serif",
  "Bodoni MT, serif",
  "Rockwell, serif",
  "Didot, serif"
];
